services:
  study_pg:
    container_name: study_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - '5438:5432'

  study_redis:
    container_name: study_redis
    image: redis:alpine
    restart: always
    env_file:
      - docker.env
    ports:
      - '6380:6379'